### ISSUE TITLE
chillup support

### ISSUE THREAD

**Issue by Cokemonkey11** [eGlint/wurstNoiselib#1]
```
$ chillup --index

To make your own wurst library searchable, it must be:

-   Uploaded to GitHub in a public repository
-   Tagged with the `wurst` and `dependency` topics
```

**Comment by eGlint** [comment]
![image](https://user-images.githubusercontent.com/15387733/112913008-1246a780-90b6-11eb-9c97-9c746153c0d2.png)

wurstNoiselib is now searchable in chillup.

Thanks for notifying me about this! 😃
